name: Update check run
description: Update check run action

inputs:
  check-run-ids:
    description: 'List of Check Run IDs'
    required: false

  check-run-name:
    description: 'Name of the check run'
    required: false

  conclusion:
    description: 'Conclusion of the check run'
    required: true

  title:
    description: 'Title of the check run body'
    required: false

  status:
    description: 'Status of check run'
    required: false

  summary:
    description: 'Summary of the check run body'
    required: false

  text:
    description: 'Text of the check run body'
    required: false

  head-sha:
    description: 'The SHA of the pull request head.'
    default: ${{ github.event.pull_request.head.sha }}
    required: false

  target-repo:
    description: 'Target Repository name'
    default: ${{ github.repository }}
    required: false

  target-pr-number:
    description: 'Target Pull Request number'
    required: false

  github-token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Target SHA
      id: get-target-sha
      if: ${{ inputs.check-run-name && !inputs.check-run-ids }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const targetPrNumber = "${{ inputs.target-pr-number }}";
          const targetRepo = "${{ inputs.target-repo }}";

          const [owner, repo] = targetRepo.split('/');
          let sha = "${{ inputs.head-sha || github.sha }}";

          if (targetPrNumber) {
            const prNumber = parseInt(targetPrNumber, 10);
            if (isNaN(prNumber)) {
             throw new Error(`Invalid PR number: ${targetPrNumber}`);
            }
          
            const pr = await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: prNumber
            });
          
            sha = pr.data.head.sha;
          }
          return sha;

    - name: List Check Runs For Commit Sha
      id: list-check-runs
      if: ${{ steps.get-target-sha.outputs.result }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const targetRepo = "${{ inputs.target-repo }}";
          const [owner, repo] = targetRepo.split('/');
          const checkRunsResponse = await github.rest.checks.listForRef({ 
            owner: owner, 
            repo: repo, 
            ref: ${{ steps.get-target-sha.outputs.result }}
          });
          
          return checkRunsResponse.data.check_runs;

    - name: Find Check Run By Name
      id: find-check-run
      if: ${{ steps.list-check-runs.outputs.result }}
      uses: actions/github-script@v7
      with:
        script: |
          const checkRuns = ${{ steps.list-check-runs.outputs.result }}
          const checkRunName = "${{ inputs.check-run-name }}"
          const checkRun = checkRuns.find(
            (checkRun) => checkRun.name === checkRunName        
          );
          if (!checkRun) {
            core.setFailed(`Check run with name "${checkRunName}" not found.`);
          } else {
            return checkRun.id;
          }

    - name: Update Check Run
      id: update-check-run
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const [owner, repo] = "${{ inputs.target-repo }}".split('/');
          let checkRunIds = "${{ inputs.check-run-ids }}";
          const checkRunName = "${{ inputs.check-run-name }}";
          if (!checkRunIds && !checkRunName) {
            core.setFailed('One of check-run-ids or check-run-name must be provided.');
          }
          
          checkRunIds = checkRunIds ? checkRunIds.split(',') : [${{ steps.find-check-run.outputs.result }}];
          for (const checkRunId of checkRunIds) {                                                                  
            const checkRunData = {
              owner: owner,
              repo: repo,
              check_run_id: checkRunId,
            };
          
            if (checkRunIds.length > 1) {
              const conclusion = "${{ inputs.conclusion }}";
              if (conclusion) {
                checkRunData.conclusion = conclusion;
              }
              await github.rest.checks.update(checkRunData);
              continue;
            }
          
            const optionalInputs = {
              name: "${{ inputs.check-run-name }}",
              status: "${{ inputs.status }}",
              conclusion: "${{ inputs.conclusion }}",
            }; 
          
            Object.entries(optionalInputs).forEach(([key, value]) => {
                if (value) checkRunData[key] = value;
            });
          
            const checkRunTitle = "${{ inputs.title }}"
            const checkRunSummary = "${{ inputs.summary }}"
            const checkRunText = "${{ inputs.text }}"
          
            if (checkRunTitle && checkRunSummary) {
              checkRunData.output = {
                title: checkRunTitle,
                summary: checkRunSummary
              };
          
              if (checkRunText) {
                checkRunData.output.text = checkRunText;
              }
            }
          
            await github.rest.checks.update(checkRunData);
          }
