apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-management-device-deployment
  labels:
    app: iot-management-device
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iot-management-device
  template:
    metadata:
      labels:
        app: iot-management-device
    spec:
      containers:
        - name: iot-management-device
          image: iot-management-device:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: host
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: port
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: db_name
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  name: nats-configmap
                  key: nats_uri
